apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "daily-scraper.fullname" . }}-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ template "daily-scraper.name" . }}
      release: {{ .Release.Name }}
